In [22]:
import pandas as pd
import pickle
import sys
sys.path.insert(1, '../assets/src')

## Basic Statistics

In [15]:
with open(r'../assets/data/STATS.pkl', 'rb') as f:
    stats_df = pickle.load(f)

In [16]:
stats_df

   Death  Confirmed  Investigating  Reported
0      0         15            168       882

## Coordinates

In [13]:
with open(r'../assets/data/coordinates_df.pkl', 'rb') as f:
    coordinates_df = pickle.load(f)

In [14]:
coordinates_df

,loc_id,address,latitude,longitude
0,0,"West Kowloon Station, Hong Kong",22.304080,114.166501
1,1,"Block 1, Site 11, Whampoa Garden, Hong Kong",22.305096,114.190610
2,2,"Wah Cheung House, Ching Wah Court, Hong Kong",22.348820,114.101020
3,3,"Tower 2, The Coronation, Hong Kong",22.309601,114.165802
4,4,"Cheung Hong Estate, Hong Mei House, Hong Kong",22.350433,114.099415
5,5,"Four Seasons Hotel Hong Kong, Hong Kong",22.286634,114.156700
6,6,"W Hong Kong, Hong Kong",22.304636,114.160593
7,7,"The Ritz-Carlton, Hong Kong",22.303165,114.160212
8,8,"8/F, Tin Hei House, Tin Ping Estate, Hong Kong",22.503551,114.133889
9,9,"Block 2, Tseung Kwan O Plaza, Hong Kong",22.308929,114.262603
10,10,"Universal Towers, Hong Kong",22.291657,114.199545
11,11,"South Hillcrest, Hong Kong",22.412291,113.983503
12,12,"Tower 1, Lake Silver, Hong Kong",22.428621,114.243974
13,13,"Empire Hotel Kowloon, Tsim Sha Tsui, Hong Kong",22.300866,114.175152
14,14,"Floor 23, Li Po Chun Chambers, Hong Kong",22.286215,114.154002
15,15,"26/F, Tower 1A, Oceanaire, Hong Kong",22.415273,114.223638
16,16,"Alva Hotel by Royal, Hong Kong",22.383572,114.208377
17,17,"Luk Kwai House Kwai Chung Estate, Hong Kong",22.368088,114.128424
18,18,"Lo Wu Customs Checkpoint, Hong Kong",22.528975,114.113266
19,19,"Kai Tak Cruise Terminal, Hong Kong",22.307013,114.212063
20,20,"""Enhanted Princess"" Cruise, Hong Kong",22.307013,114.212063
21,21,"High Speed Rail, Hong Kong",22.304080,114.166501

In [10]:
# coordinates_df.loc[21, 'latitude'] = 22.304080
# coordinates_df.loc[21, 'longitude'] = 114.166501

In [11]:
# with open(r'../assets/data/coordinates_df.pkl', 'wb') as f:
#     pickle.dump(coordinates_df, f)

## Casese

In [19]:
with open(r'../assets/data/CASES.pkl', 'rb') as f:
    cases_df = pickle.load(f)

In [24]:
from webscraper import fetch_cases
fetch_cases()

IndexError: list index out of range

In [20]:
cases_df

,casenum,status,age,gender,date,residence,hospital,desc
0,15,Hospitalised,72,Female,2020-02-02,Hong Kong,Princess Margaret Hospital,The female patient is the mother of case no 13...
1,14,Hospitalised,80,Male,2020-02-01,Hong Kong,Princess Margaret Hospital,The patient lives in Luk Kwai House in Kwai Ch...
2,13,Deceased,39,Male,2020-01-31,Hong Kong,Princess Margaret Hospital,The male patient with long term illness lives ...
3,12,Hospitalised,75,Male,2020-01-30,Hong Kong,Princess Margaret Hospital,The 75 year-old patient lives in Cheung Hong E...
4,11,Hospitalised,37,Female,2020-01-30,Hong Kong,Princess Margaret Hospital,\nThe female patient is the daughter of a coup...
5,10,Serious,72,Male,2020-01-29,Wuhan,Princess Margaret Hospital,The male patient arrived in Hong Kong by plane...
6,9,Hospitalised,73,Female,2020-01-29,Wuhan,Princess Margaret Hospital,The female patient arrived in Hong Kong by pla...
7,8,Hospitalised,64,Male,2020-01-26,Wuhan,Princess Margaret Hospital,The 64 year-old male patient from Wuhan has lo...
8,7,Critical,68,Female,2020-01-26,Hong Kong,Princess Margaret Hospital,The 68 year-old female patient lives in Fan Li...
9,6,Hospitalised,47,Male,2020-01-26,Hong Kong,Princess Margaret Hospital,The patient lied about his job of an accountan...
10,5,Hospitalised,63,Male,2020-01-24,Wuhan,Princess Margaret Hospital,The 63 year-old male patient came from Wuhan w...
11,4,Hospitalised,62,Female,2020-01-24,Wuhan,Princess Margaret Hospital,The 62 year-old female patient came from Wuhan...
12,3,Hospitalised,62,Female,2020-01-24,Wuhan,Princess Margaret Hospital,The female patient took High Speed Rail from W...
13,2,Serious,56,Male,2020-01-23,Hong Kong,Princess Margaret Hospital,"The patient flew from Wuhan to ShenZhen, then ..."
14,1,Hospitalised,39,Male,2020-01-23,Wuhan,Princess Margaret Hospital,The patient travelled to Hong Kong by high spe...