In [2]:
import pandas as pd
import pickle
import numpy as np
import sys
import requests
import json
import pyodbc
import csv
sys.path.insert(1, '../src')

## Hospitals Addresses (this one should be static)

In [33]:
with open(r'../data/HOSPITALS.pkl', 'rb') as f:
    hospitals_df = pickle.load(f)

In [34]:
hospitals_df.head()

,id,address,latitude,longitude,category
0,0,Alice Ho Miu Ling Nethersole Hospital,22.458515,114.174944,Hospital
1,1,North District Hospital,22.496759,114.124606,Hospital
2,2,North Lantau Hospital,22.282335,113.939275,Hospital
3,3,Pok Oi Hospital,22.445444,114.041639,Hospital
4,4,Pamela Youde Nethersole Eastern Hospital,22.270224,114.236770,Hospital

In [35]:
# hospitals_df.to_csv(r'../data/HOSPITALS.tsv', index=False, sep='\t')

## High Risk Address

In [27]:
from webscraper import fetch_highrisk

In [28]:
high_risk_df = fetch_highrisk()

In [30]:
# with open(r'../data/HIGH_RISK.pkl', 'wb') as f:
#     pickle.dump(high_risk_df, f)

In [32]:
high_risk_df.to_csv(r'../data/HIGH_RISK.tsv', index=False, sep='\t')

In [11]:
high_risk_df

,id,sub_district_zh,sub_district_en,action_zh,action_en,location_en,location_zh,remarks_en,remarks_zh,source_url_1,source_url_2,start_date,end_date,lat,lng,type,case_no,case
0,2739d8de-60e1-56a4-bd5a-d0c0af86b1a9,-,-,交通,Transport,Cathay Pacific CX252 (seat 48D),國泰航空 CX252（座位 48D ）,London to Hong Kong,由倫敦抵港,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,2020-04-13,2020-04-14,,,self,1014,1014
1,a43ccbfa-9dda-5edd-8a4a-5756aa25b687,-,-,交通,Transport,Virgin Atlantic VS206 (seat 61A）,維珍航空 VS206（座位 61A ),London to Hong Kong,由倫敦抵港,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,2020-04-13,2020-04-14,,,self,1016,1016
2,e742bac4-2eac-518c-8db1-e501d350ed2d,-,-,交通,Transport,Qatar Airways QR818 (seat 3A),卡塔爾航空 QR818（座位 3A ）,Doha to Hong Kong,由多哈抵港,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,2020-04-14,2020-04-14,,,self,1017,1017
3,08c2bbc4-d1db-5934-a2ca-031570f25e36,-,-,交通,Transport,Cathay Pacific CX881 (seat 44D),國泰航空 CX881（座位 44D）,Los Angeles to Hong Kong,由洛杉磯抵港,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,2020-04-12,2020-04-13,,,self,1011,1011
4,70ded552-7e57-599b-8cdb-a70ff107b7d0,-,-,交通,Transport,Cathay Pacific CX881 (seat 30A),國泰航空 CX881（座位 30A）,Los Angeles to Hong Kong,由洛杉磯抵港,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,2020-04-12,2020-04-13,,,self,1012,1012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2828,a4aa1f55-7699-5029-ad37-427abcb38d9c,屯門,Tuen Mun,住宿,Residence,"Tower 11, Avignon",星堤 11座,,,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,NaT,NaT,22.375214,113.999066,self,1013,1013
2829,17fb46dc-2837-5c4c-927c-4261e432fa24,荃灣,Tsuen Wan,住宿,Residence,Silka Tsuen Wan Hotel,荃灣絲麗酒店,,,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,NaT,NaT,22.369159,114.138975,self,1015,1015
2830,f23a420c-144b-51b7-a3dc-d5400cd353b3,灣仔,Wan Chai,住宿,Residence,CHI Residences 138,太極軒 138,,,https://nandiheath.github.io/chp-archive/data/...,https://nandiheath.github.io/chp-archive/data/...,NaT,NaT,22.276457,114.173861,self,1017,1017
2831,ff79f245-4652-57dc-a7ea-26a36fd42012,旺角,Mong Kok,住宿,Residence,Metropark Hotel,維景酒店,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.281292,114.192157,self,1018,1018
2832,30ae8be0-923a-5dda-99a4-4dca0bcf68a8,深水埗,Sham Shui Po,住宿,Residence,"Block 2, Cronin Garden, 2 Po On Road",保安道2號樂年花園第二座,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.3362789,114.1610629,self,1018,1018

In [36]:
with open(r'../data/HIGH_RISK.pkl', 'rb') as f:
    high_risk_df = pickle.load(f)

In [37]:
high_risk_df

,id,sub_district_zh,sub_district_en,action_zh,action_en,location_en,location_zh,remarks_en,remarks_zh,source_url_1,source_url_2,start_date,end_date,lat,lng,type,case_no,case
0,08c2bbc4-d1db-5934-a2ca-031570f25e36,,#N/A,交通,Transport,Cathay Pacific CX881 (seat 44D),,Los Angeles to Hong Kong,由洛杉磯抵港,https://www.chp.gov.hk/files/pdf/flights_train...,https://www.chp.gov.hk/files/pdf/flights_train...,2020-04-12,2020-04-13,,,self,,
1,70ded552-7e57-599b-8cdb-a70ff107b7d0,,#N/A,交通,Transport,Cathay Pacific CX881 (seat 30A),,Los Angeles to Hong Kong,由洛杉磯抵港,https://www.chp.gov.hk/files/pdf/flights_train...,https://www.chp.gov.hk/files/pdf/flights_train...,2020-04-12,2020-04-13,,,self,,
2,0115d69a-dc7e-5928-ae54-36ac35812ce7,-,-,交通,Transport,Virgin Atlantic VS206 (seat 59G),維珍航空 VS206 ( 座位 59G ),London to Hong Kong,由倫敦抵港,https://www.chp.gov.hk/files/pdf/flights_train...,https://www.chp.gov.hk/files/pdf/flights_train...,2020-04-11,2020-04-12,,,self,1006,1006
3,11353905-edbf-5820-89b4-fd222f612e3c,-,-,交通,Transport,Virgin Atlantic VS206 (seat 55G),維珍航空 VS206 ( 座位 55G ),London to Hong Kong,由倫敦抵港,https://www.chp.gov.hk/files/pdf/flights_train...,https://www.chp.gov.hk/files/pdf/flights_train...,2020-04-11,2020-04-12,,,self,1010,1010
4,caa1dc3f-3ce8-5750-a23a-24a184cf1226,-,-,交通,Transport,Cathay Pacific CX252 (seat 60H),國泰航空 CX252（座位 60H ）,London to Hong Kong,由倫敦抵港,https://www.chp.gov.hk/files/pdf/flights_train...,https://www.chp.gov.hk/files/pdf/flights_train...,2020-04-09,2020-04-10,,,self,994,994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,dedfdcfa-1b2a-5aff-bfb2-4617f3fcf557,大圍,Tai Wai,住宿,Residence,"Block 2, Carado Garden",雲疊花園 2座,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.368507,114.177542,self,1007,1007
2816,54bf17cd-9ea6-549f-9e38-1cbe15232d3a,半山區,Mid-levels,住宿,Residence,"Block 3, Garden Terrace",花園台 3座,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.2756382,114.1541769,self,1009,1009
2817,a4aa1f55-7699-5029-ad37-427abcb38d9c,屯門,Tuen Mun,住宿,Residence,"Tower 11, Avignon",星堤 11座,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.375214,113.999066,self,1013,1013
2818,17fb46dc-2837-5c4c-927c-4261e432fa24,荃灣,Tsuen Wan,住宿,Residence,Silka Tsuen Wan Hotel,荃灣絲麗酒店,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.369159,114.138975,self,1015,1015
2819,f23a420c-144b-51b7-a3dc-d5400cd353b3,灣仔,Wan Chai,住宿,Residence,CHI Residences 138,太極軒 138,,,https://www.chp.gov.hk/files/pdf/building_list...,https://www.chp.gov.hk/files/pdf/building_list...,NaT,NaT,22.276457,114.173861,self,1017,1017

## Casese

In [52]:
with open(r'../data/CASES.pkl', 'rb') as f:
    cases_df = pickle.load(f)

In [45]:
from webscraper import fetch_cases

cases_df = fetch_cases()

In [46]:
cases_df

,case_no,onset_date,confirmation_date,gender,age,hospital_zh,hospital_en,status,status_zh,status_en,type_zh,type_en,citizenship_zh,citizenship_en,detail_zh,detail_en,classification,classification_zh,classification_en,source_url
1017,1018,2020-04-13,2020-04-16,F,19,明愛醫院,Caritas Medical Centre,hospitalised,住院中,Hospitalised,確診,Confirmed,旺角,Mong Kok,患者為英國留學生，過往健康良好。4 月 1 日從英國返港，4 月 2 日測試結果呈陰性，抵港...,,imported,輸入個案,Imported,https://gia.info.gov.hk/general/202004/16/P202...
1016,1017,none,2020-04-15,M,36,東區尤德夫人那打素醫院,Pamela Youde Nethersole Eastern Hospital,hospitalised,住院中,Hospitalised,確診,Confirmed,灣仔,Wan Chai,患者居於荷蘭，4 月 14 日抵港，強制家居檢疫人士。患者無病徵。,The patient resides in the Netherlands and ret...,imported,輸入個案,Imported,https://gia.info.gov.hk/general/202004/15/P202...
1015,1016,2020-03-17,2020-04-15,M,42,伊利沙伯醫院,Queen Elizabeth Hospital,hospitalised,住院中,Hospitalised,確診,Confirmed,不明,Uncertain,患者與妻子居於英國，4 月 14 日返港，3 月 17 日開始發燒及咳嗽。患者妻子亦有病徵但...,The patient resides in the UK with his wife an...,imported,輸入個案,Imported,https://gia.info.gov.hk/general/202004/15/P202...
1014,1015,2020-04-11,2020-04-15,F,60,瑪嘉烈醫院,Princess Margaret Hospital,hospitalised,住院中,Hospitalised,確診,Confirmed,荃灣,Tsuen Wan,患者 2 月尾至 4 月 10 日到過摩洛哥，乘摩洛哥包機回港，4 月 10 日在廣州白雲機...,The patient was in Morroco between late Februa...,imported,輸入個案,Imported,https://gia.info.gov.hk/general/202004/15/P202...
1013,1014,none,2020-04-15,M,22,律敦治醫院,Ruttonjee Hospital,hospitalised,住院中,Hospitalised,確診,Confirmed,不明,Uncertain,患者留學英國，4 月 14 日返港，由亞洲博覽館送院。 患者無病徵。,The patient studies in the UK and returned to ...,imported,輸入個案,Imported,https://gia.info.gov.hk/general/202004/15/P202...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,2020-01-23,2020-01-24,M,63,瑪嘉烈醫院,Princess Margaret Hospital,discharged,出院,Discharged,確診,Confirmed,武漢,Wuhan,男患者與妻子於 1 月 24 日從武漢來港探望居住在馬鞍山銀湖天峰的女兒，到醫院求醫，夫婦須...,The 63 year-old male patient came from Wuhan w...,imported,輸入個案,Imported,https://www.thestandnews.com/politics/%E6%AD%A...
3,4,2020-01-23,2020-01-24,F,62,瑪嘉烈醫院,Princess Margaret Hospital,discharged,出院,Discharged,確診,Confirmed,武漢,Wuhan,62 歲女患者與丈夫於 1 月 24 日從武漢來港探望居住在馬鞍山銀湖天峰的女兒。二人與女兒...,The 62 year-old female patient came from Wuhan...,imported,輸入個案,Imported,https://www.thestandnews.com/politics/%E6%AD%A...
2,3,2020-01-20,2020-01-24,F,62,瑪嘉烈醫院,Princess Margaret Hospital,discharged,出院,Discharged,確診,Confirmed,武漢,Wuhan,1 月 19 日乘搭高鐵由武漢到港，入住屯門倚嶺南庭。自 1 月 20 日起出現病徵，23 ...,The female patient took a high-speed rail trai...,imported,輸入個案,Imported,https://news.rthk.hk/rthk/ch/component/k2/1504...
1,2,2020-01-18,2020-01-23,M,56,瑪嘉烈醫院,Princess Margaret Hospital,discharged,出院,Discharged,確診,Confirmed,馬鞍山,Ma On Shan,1 月 10 日獨自前往武漢，1 月 19 日由武漢乘坐航班前往深圳，再經羅湖乘東鐵轉馬鐵返...,The patient travelled to Wuhan on Jan 10. He f...,imported,輸入個案,Imported,https://hd.stheadline.com/news/realtime/hk/168...
0,1,2020-01-21,2020-01-23,M,39,瑪嘉烈醫院,Princess Margaret Hospital,discharged,出院,Discharged,確診,Confirmed,武漢,Wuhan,1 月 21 日搭高鐵來港，同日出現發燒及鼻塞，於西九龍站被發現發燒，即時送院。同行 4 名...,The patient travelled to Hong Kong via high-sp...,imported,輸入個案,Imported,https://www.thestandnews.com/society/%E6%AD%A6...

In [14]:
# with open(r'../data/CASES.pkl', 'wb') as f:
#     pickle.dump(cases_df, f)

In [60]:
cases_df.replace(r'\n',' ', regex=True).replace(r'\r',' ', regex=True).to_csv(r'../data/CASES.tsv', index=False, sep='\t')

## Awaiting

In [36]:
with open(r'../data/AWAITING.pkl', 'rb') as f:
    awaiting_df = pickle.load(f)

In [37]:
from webscraper import fetch_awaiting_time

awaiting_df = fetch_awaiting_time()

In [38]:
# with open(r'../data/AWAITING.pkl', 'wb') as f:
#     pickle.dump(awaiting_df, f)

In [40]:
# awaiting_df.to_csv(r'../data/AWAITING.tsv', index=False, sep='\t')

## Basic Statistics

In [17]:
with open(r'../data/STATS.pkl', 'rb') as f:
    stats_df = pickle.load(f)

In [18]:
stats_df

  death confirmed investigating reported discharged ruled_out
0     2        81           116     1731         19      1538

In [19]:
from wuhan_functions import calculate_stats

In [20]:
stats_df = calculate_stats(cases_df)

In [22]:
stats_df

   death  confirmed  discharged  hospitalised
0      4       1017         434           554

In [23]:
with open(r'../data/STATS.pkl', 'wb') as f:
    pickle.dump(stats_df, f)

In [24]:
stats_df.to_csv(r'../data/STATS.csv', index=False)

## Load pickle file

In [2]:
from wuhan_functions import load_data_csv, load_data_pkl

In [3]:
len(load_data_pkl())

4

In [4]:
len(load_data_csv())

4

## Load data using sql

In [64]:
server = 'datavisualizationfti.database.windows.net'
database = 'myVisualizationData'
username = 'azureuser'
password = 'Pass7890'
driver = 'SQL Server'  


cnxn = pyodbc.connect('DRIVER={' + driver + '};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)

In [66]:
high_risk_df = pd.read_sql('SELECT * FROM HIGH_RISK', cnxn)
cnxn.close()

In [3]:
from wuhan_functions import load_data_sql

In [4]:
cases_df, high_risk_df, stats_df, hospital_awaiting_df = load_data_sql()